import AddRestaurantForm from './AddRestaurantForm';
import AddRestaurantModal from './AddRestuarntModal';
import AddSelect from './AddSelect';
import Button from './Button';
import CategoryImage from './CategoryImage';
import DeleteQustion from './DeleteQustion';
import DeleteQustionModal from './DeleteQuestionModal';
import DescriptionInput from './DescriptionInput';
import FavoriteImage from './FavoriteImage';
import FilterBox from './FilterBox';
import Header from './Header';
import LinkInput from './LinkInput';
import Modal from './Modal';
import NameInput from './NameInput';
import RestaurantBox from './RestaurantBox';
import RestaurantBoxes from './RestaurantBoxes';
import RestaurantDetail from './RestaurantDetail';
import RestaurantDetailModal from './RestaurantDetailModal';
import RestaurantTab from './RestaurantTab';

window.customElements.define('add-restaurant-form', AddRestaurantForm);
window.customElements.define('add-restaurant-modal', AddRestaurantModal);
window.customElements.define('add-select', AddSelect);
window.customElements.define('lunch-button', Button);
window.customElements.define('category-image', CategoryImage);
window.customElements.define('delete-question', DeleteQustion);
window.customElements.define('delete-question-modal', DeleteQustionModal);
window.customElements.define('description-input', DescriptionInput);
window.customElements.define('favorite-image', FavoriteImage);
window.customElements.define('filter-box', FilterBox);
window.customElements.define('lunch-header', Header);
window.customElements.define('link-input', LinkInput);
window.customElements.define('lunch-modal', Modal);
window.customElements.define('name-input', NameInput);
window.customElements.define('restaurant-box', RestaurantBox);
window.customElements.define('restaurant-boxes', RestaurantBoxes);
window.customElements.define('restaurant-detail', RestaurantDetail);
window.customElements.define('restaurant-detail-modal', RestaurantDetailModal);
window.customElements.define('restaurant-tab', RestaurantTab);
